import { z } from "zod";
import { pgTable, serial, integer, text, jsonb, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";

export const axleConfigurations = ["4x2", "6x2", "6x4", "8x4"] as const;
export type AxleConfiguration = typeof axleConfigurations[number];

export const cabinTypes = ["Fernverkehr", "Verteiler", "Nahverkehr", "Kipper"] as const;
export type CabinType = typeof cabinTypes[number];

export const technicalSpecsSchema = z.object({
  zulaessigesGesamtgewicht: z.number().min(0).optional(),
  zugGesamtgewicht: z.number().min(0).optional(),
  achskonfiguration: z.enum(axleConfigurations).optional(),
  nutzlast: z.number().min(0).optional(),
  leistungKW: z.number().min(0).optional(),
  leistungPS: z.number().min(0).optional(),
  drehmoment: z.number().min(0).optional(),
  batterieKapazitaet: z.number().min(0).optional(),
  tankKapazitaet: z.number().min(0).optional(),
  reichweite: z.number().min(0).optional(),
  ladeLeistungAC: z.number().min(0).optional(),
  ladeLeistungDC: z.number().min(0).optional(),
  fahrerhaus: z.enum(cabinTypes).optional(),
  laenge: z.number().min(0).optional(),
  hoehe: z.number().min(0).optional(),
});

export type TechnicalSpecs = z.infer<typeof technicalSpecsSchema>;

export const truckParametersSchema = z.object({
  name: z.string().min(1, "Name ist erforderlich"),
  type: z.enum(["diesel", "electric"]),
  purchasePrice: z.number().min(0, "Kaufpreis muss positiv sein"),
  annualMileage: z.number().min(0, "Jahreskilometer muss positiv sein"),
  fuelCostPerUnit: z.number().min(0, "Kraftstoff-/Stromkosten müssen positiv sein"),
  maintenanceCostAnnual: z.number().min(0, "Wartungskosten müssen positiv sein"),
  insuranceCostAnnual: z.number().min(0, "Versicherungskosten müssen positiv sein"),
  expectedLifespanYears: z.number().min(1).max(30, "Lebensdauer muss zwischen 1 und 30 Jahren liegen"),
  fuelEfficiency: z.number().min(0, "Kraftstoffeffizienz muss positiv sein"),
  technicalSpecs: technicalSpecsSchema.optional(),
});

export type TruckParameters = z.infer<typeof truckParametersSchema>;

export const taxIncentiveRegions = ["bundesfoerderung", "bayern", "baden-wuerttemberg", "nordrhein-westfalen", "niedersachsen", "keine"] as const;
export type TaxIncentiveRegion = typeof taxIncentiveRegions[number];

export const operationProfileSchema = z.object({
  dailyKm: z.number().min(0),
  dailyKmP90: z.number().min(0),
  stopsPerDay: z.number().min(0),
  stopMinutes: z.number().min(0),
  workDaysPerYear: z.number().min(0),
  opportunityCharging: z.boolean().optional().default(false),
  opportunityChargeMinutes: z.number().min(0).optional().default(0),
  opportunityChargePowerKw: z.number().min(0).optional().default(150),
  publicChargeShare: z.number().min(0).max(100).optional().default(0),
  publicChargeCostPerKwh: z.number().min(0).optional().default(0),
  p90SharePercent: z.number().min(0).max(100).optional().default(10),
  downtimeCostPerDay: z.number().min(0).optional().default(0),
  infrastructureCapex: z.number().min(0).optional().default(0),
  infrastructureOpexAnnual: z.number().min(0).optional().default(0),
  infrastructureLifetimeYears: z.number().min(1).max(30).optional().default(10),
});

export type OperationProfile = z.infer<typeof operationProfileSchema>;

export const comparisonRequestSchema = z.object({
  dieselTruck: truckParametersSchema,
  electricTruck1: truckParametersSchema,
  electricTruck2: truckParametersSchema,
  timeframeYears: z.number().min(1).max(30),
  taxIncentiveRegion: z.enum(taxIncentiveRegions).optional().default("bundesfoerderung"),
  operationProfile: operationProfileSchema.optional(),
});

export type ComparisonRequest = z.infer<typeof comparisonRequestSchema>;

export const yearCostBreakdownSchema = z.object({
  year: z.number(),
  purchaseCost: z.number(),
  fuelCost: z.number(),
  maintenanceCost: z.number(),
  insuranceCost: z.number(),
  depreciationCost: z.number(),
  infrastructureCost: z.number(),
  downtimeCost: z.number(),
  totalCost: z.number(),
  cumulativeCost: z.number(),
});

export type YearCostBreakdown = z.infer<typeof yearCostBreakdownSchema>;

export const truckAnalysisSchema = z.object({
  name: z.string(),
  type: z.enum(["diesel", "electric"]),
  totalCostOfOwnership: z.number(),
  yearlyBreakdown: z.array(yearCostBreakdownSchema),
  totalFuelCost: z.number(),
  totalMaintenanceCost: z.number(),
  totalInsuranceCost: z.number(),
  depreciation: z.number(),
  totalInfrastructureCost: z.number(),
  totalDowntimeCost: z.number(),
  environmentalImpact: z.object({
    totalCO2Emissions: z.number(),
    totalFuelConsumed: z.number(),
    fuelUnit: z.enum(["liters", "kWh"]),
  }),
  technicalSpecs: technicalSpecsSchema.optional(),
});

export type TruckAnalysis = z.infer<typeof truckAnalysisSchema>;

export const breakEvenAnalysisSchema = z.object({
  truck1Name: z.string(),
  truck2Name: z.string(),
  breakEvenYear: z.number().nullable(),
  breakEvenMonth: z.number().nullable(),
  totalSavings: z.number(),
});

export type BreakEvenAnalysis = z.infer<typeof breakEvenAnalysisSchema>;

export const comparisonResultSchema = z.object({
  dieselAnalysis: truckAnalysisSchema,
  electric1Analysis: truckAnalysisSchema,
  electric2Analysis: truckAnalysisSchema,
  dieselVsElectric1: breakEvenAnalysisSchema,
  dieselVsElectric2: breakEvenAnalysisSchema,
  bestElectricOption: z.enum(["electric1", "electric2"]),
  maxSavings: z.number(),
  timeframeYears: z.number(),
  environmentalComparison: z.object({
    bestElectricCO2Saved: z.number(),
    bestElectricName: z.string(),
  }),
});

export type ComparisonResult = z.infer<typeof comparisonResultSchema>;

export interface RegionalIncentive {
  region: string;
  federalCredit: number;
  stateCredit: number;
  totalIncentive: number;
  description: string;
}

export const regionalIncentives: Record<TaxIncentiveRegion, RegionalIncentive> = {
  "bundesfoerderung": {
    region: "Nur Bundesförderung",
    federalCredit: 80000,
    stateCredit: 0,
    totalIncentive: 80000,
    description: "KsNI-Förderung für klimaschonende Nutzfahrzeuge (bis zu 80% der Mehrkosten)",
  },
  "bayern": {
    region: "Bayern",
    federalCredit: 80000,
    stateCredit: 10000,
    totalIncentive: 90000,
    description: "Bundesförderung + Bayerische Förderung für E-Nutzfahrzeuge",
  },
  "baden-wuerttemberg": {
    region: "Baden-Württemberg",
    federalCredit: 80000,
    stateCredit: 15000,
    totalIncentive: 95000,
    description: "Bundesförderung + BW-e-Gutschein für E-Nutzfahrzeuge",
  },
  "nordrhein-westfalen": {
    region: "Nordrhein-Westfalen",
    federalCredit: 80000,
    stateCredit: 8000,
    totalIncentive: 88000,
    description: "Bundesförderung + NRW progres.nrw Emissionsarme Mobilität",
  },
  "niedersachsen": {
    region: "Niedersachsen",
    federalCredit: 80000,
    stateCredit: 5000,
    totalIncentive: 85000,
    description: "Bundesförderung + Niedersächsische Klimaschutzförderung",
  },
  "keine": {
    region: "Keine Förderung",
    federalCredit: 0,
    stateCredit: 0,
    totalIncentive: 0,
    description: "Berechnung ohne Förderungen",
  },
};

export const presetTruckModels: Record<string, TruckParameters> = {
  "mercedes-actros": {
    name: "Mercedes-Benz Actros",
    type: "diesel",
    purchasePrice: 155000,
    annualMileage: 120000,
    fuelCostPerUnit: 1.65,
    maintenanceCostAnnual: 14000,
    insuranceCostAnnual: 11000,
    expectedLifespanYears: 12,
    fuelEfficiency: 32,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 18000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "4x2",
      nutzlast: 26000,
      leistungKW: 350,
      leistungPS: 476,
      drehmoment: 2300,
      tankKapazitaet: 400,
      reichweite: 1200,
      fahrerhaus: "Fernverkehr",
      laenge: 6200,
      hoehe: 3950,
    },
  },
  "man-tgx": {
    name: "MAN TGX",
    type: "diesel",
    purchasePrice: 150000,
    annualMileage: 115000,
    fuelCostPerUnit: 1.65,
    maintenanceCostAnnual: 13500,
    insuranceCostAnnual: 10500,
    expectedLifespanYears: 12,
    fuelEfficiency: 33,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 18000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "4x2",
      nutzlast: 25000,
      leistungKW: 340,
      leistungPS: 460,
      drehmoment: 2300,
      tankKapazitaet: 390,
      reichweite: 1150,
      fahrerhaus: "Fernverkehr",
      laenge: 6100,
      hoehe: 3900,
    },
  },
  "scania-r-series": {
    name: "Scania R-Serie",
    type: "diesel",
    purchasePrice: 160000,
    annualMileage: 120000,
    fuelCostPerUnit: 1.65,
    maintenanceCostAnnual: 14500,
    insuranceCostAnnual: 11500,
    expectedLifespanYears: 12,
    fuelEfficiency: 31,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 18000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "4x2",
      nutzlast: 26000,
      leistungKW: 370,
      leistungPS: 500,
      drehmoment: 2550,
      tankKapazitaet: 420,
      reichweite: 1300,
      fahrerhaus: "Fernverkehr",
      laenge: 6300,
      hoehe: 4000,
    },
  },
  "volvo-fh": {
    name: "Volvo FH",
    type: "diesel",
    purchasePrice: 158000,
    annualMileage: 118000,
    fuelCostPerUnit: 1.65,
    maintenanceCostAnnual: 14200,
    insuranceCostAnnual: 11200,
    expectedLifespanYears: 12,
    fuelEfficiency: 32,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 18000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "4x2",
      nutzlast: 25500,
      leistungKW: 355,
      leistungPS: 483,
      drehmoment: 2400,
      tankKapazitaet: 410,
      reichweite: 1250,
      fahrerhaus: "Fernverkehr",
      laenge: 6200,
      hoehe: 3980,
    },
  },
  "daf-xg": {
    name: "DAF XG+",
    type: "diesel",
    purchasePrice: 162000,
    annualMileage: 120000,
    fuelCostPerUnit: 1.65,
    maintenanceCostAnnual: 14000,
    insuranceCostAnnual: 11000,
    expectedLifespanYears: 12,
    fuelEfficiency: 30,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 18000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "4x2",
      nutzlast: 26000,
      leistungKW: 390,
      leistungPS: 530,
      drehmoment: 2600,
      tankKapazitaet: 430,
      reichweite: 1350,
      fahrerhaus: "Fernverkehr",
      laenge: 6400,
      hoehe: 4050,
    },
  },
  "mercedes-eactros-600": {
    name: "Mercedes-Benz eActros 600",
    type: "electric",
    purchasePrice: 285000,
    annualMileage: 120000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 8000,
    insuranceCostAnnual: 10000,
    expectedLifespanYears: 15,
    fuelEfficiency: 105,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 22000,
      leistungKW: 400,
      leistungPS: 544,
      drehmoment: 2100,
      batterieKapazitaet: 621,
      reichweite: 500,
      ladeLeistungAC: 22,
      ladeLeistungDC: 400,
      fahrerhaus: "Fernverkehr",
      laenge: 6400,
      hoehe: 3950,
    },
  },
  "mercedes-eactros-400": {
    name: "Mercedes-Benz eActros 400",
    type: "electric",
    purchasePrice: 255000,
    annualMileage: 100000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7500,
    insuranceCostAnnual: 9500,
    expectedLifespanYears: 15,
    fuelEfficiency: 86,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "6x2",
      nutzlast: 21000,
      leistungKW: 400,
      leistungPS: 544,
      drehmoment: 2100,
      batterieKapazitaet: 414,
      reichweite: 480,
      ladeLeistungAC: 22,
      ladeLeistungDC: 400,
      fahrerhaus: "Verteiler",
      laenge: 6200,
      hoehe: 3900,
    },
  },
  "mercedes-eactros-300": {
    name: "Mercedes-Benz eActros 300",
    type: "electric",
    purchasePrice: 235000,
    annualMileage: 80000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7000,
    insuranceCostAnnual: 9000,
    expectedLifespanYears: 15,
    fuelEfficiency: 102,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "4x2",
      nutzlast: 20000,
      leistungKW: 400,
      leistungPS: 544,
      drehmoment: 2100,
      batterieKapazitaet: 336,
      reichweite: 330,
      ladeLeistungAC: 22,
      ladeLeistungDC: 400,
      fahrerhaus: "Nahverkehr",
      laenge: 6000,
      hoehe: 3850,
    },
  },
  "man-etgx": {
    name: "MAN eTGX (6 Batterien)",
    type: "electric",
    purchasePrice: 340000,
    annualMileage: 100000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7500,
    insuranceCostAnnual: 9500,
    expectedLifespanYears: 15,
    fuelEfficiency: 112,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 21500,
      leistungKW: 480,
      leistungPS: 653,
      drehmoment: 2400,
      batterieKapazitaet: 560,
      reichweite: 500,
      ladeLeistungAC: 22,
      ladeLeistungDC: 375,
      fahrerhaus: "Fernverkehr",
      laenge: 6300,
      hoehe: 3900,
    },
  },
  "volvo-fh-electric": {
    name: "Volvo FH Electric",
    type: "electric",
    purchasePrice: 325000,
    annualMileage: 100000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7800,
    insuranceCostAnnual: 9800,
    expectedLifespanYears: 15,
    fuelEfficiency: 110,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 22500,
      leistungKW: 490,
      leistungPS: 666,
      drehmoment: 2400,
      batterieKapazitaet: 540,
      reichweite: 345,
      ladeLeistungAC: 43,
      ladeLeistungDC: 250,
      fahrerhaus: "Fernverkehr",
      laenge: 6350,
      hoehe: 3970,
    },
  },
  "volvo-fh-aero-electric": {
    name: "Volvo FH Aero Electric (600 km)",
    type: "electric",
    purchasePrice: 355000,
    annualMileage: 120000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 8200,
    insuranceCostAnnual: 10200,
    expectedLifespanYears: 15,
    fuelEfficiency: 130,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 21500,
      leistungKW: 540,
      leistungPS: 734,
      drehmoment: 2600,
      batterieKapazitaet: 780,
      reichweite: 600,
      ladeLeistungAC: 43,
      ladeLeistungDC: 350,
      fahrerhaus: "Fernverkehr",
      laenge: 6500,
      hoehe: 4000,
    },
  },
  "volvo-fm-electric": {
    name: "Volvo FM Electric",
    type: "electric",
    purchasePrice: 305000,
    annualMileage: 90000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7500,
    insuranceCostAnnual: 9500,
    expectedLifespanYears: 15,
    fuelEfficiency: 142,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 22000,
      leistungKW: 450,
      leistungPS: 612,
      drehmoment: 2200,
      batterieKapazitaet: 540,
      reichweite: 380,
      ladeLeistungAC: 43,
      ladeLeistungDC: 250,
      fahrerhaus: "Verteiler",
      laenge: 6200,
      hoehe: 3850,
    },
  },
  "daf-xf-electric": {
    name: "DAF XF Electric",
    type: "electric",
    purchasePrice: 300000,
    annualMileage: 100000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7600,
    insuranceCostAnnual: 9600,
    expectedLifespanYears: 15,
    fuelEfficiency: 105,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 21000,
      leistungKW: 350,
      leistungPS: 476,
      drehmoment: 1700,
      batterieKapazitaet: 525,
      reichweite: 500,
      ladeLeistungAC: 22,
      ladeLeistungDC: 350,
      fahrerhaus: "Fernverkehr",
      laenge: 6250,
      hoehe: 3920,
    },
  },
  "daf-xd-electric": {
    name: "DAF XD Electric",
    type: "electric",
    purchasePrice: 280000,
    annualMileage: 80000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7200,
    insuranceCostAnnual: 9200,
    expectedLifespanYears: 15,
    fuelEfficiency: 120,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "6x2",
      nutzlast: 20000,
      leistungKW: 320,
      leistungPS: 435,
      drehmoment: 1500,
      batterieKapazitaet: 420,
      reichweite: 350,
      ladeLeistungAC: 22,
      ladeLeistungDC: 350,
      fahrerhaus: "Verteiler",
      laenge: 6000,
      hoehe: 3800,
    },
  },
  "scania-electric": {
    name: "Scania 40 R BEV (6 Batterien)",
    type: "electric",
    purchasePrice: 290000,
    annualMileage: 100000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 8200,
    insuranceCostAnnual: 10200,
    expectedLifespanYears: 15,
    fuelEfficiency: 178,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "6x4",
      nutzlast: 23000,
      leistungKW: 450,
      leistungPS: 612,
      drehmoment: 2200,
      batterieKapazitaet: 624,
      reichweite: 350,
      ladeLeistungAC: 43,
      ladeLeistungDC: 375,
      fahrerhaus: "Fernverkehr",
      laenge: 6450,
      hoehe: 4000,
    },
  },
  "renault-e-tech-t-585": {
    name: "Renault E-Tech T 585",
    type: "electric",
    purchasePrice: 300000,
    annualMileage: 90000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7200,
    insuranceCostAnnual: 9200,
    expectedLifespanYears: 15,
    fuelEfficiency: 127,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 26000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 20000,
      leistungKW: 430,
      leistungPS: 585,
      drehmoment: 1800,
      batterieKapazitaet: 585,
      reichweite: 460,
      ladeLeistungAC: 22,
      ladeLeistungDC: 250,
      fahrerhaus: "Fernverkehr",
      laenge: 6100,
      hoehe: 3850,
    },
  },
  "renault-e-tech-t-780": {
    name: "Renault E-Tech T 780",
    type: "electric",
    purchasePrice: 320000,
    annualMileage: 120000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7500,
    insuranceCostAnnual: 9500,
    expectedLifespanYears: 15,
    fuelEfficiency: 130,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 26000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 19500,
      leistungKW: 490,
      leistungPS: 666,
      drehmoment: 2000,
      batterieKapazitaet: 780,
      reichweite: 600,
      ladeLeistungAC: 22,
      ladeLeistungDC: 350,
      fahrerhaus: "Fernverkehr",
      laenge: 6300,
      hoehe: 3900,
    },
  },
  "iveco-s-eway-bev": {
    name: "Iveco S-eWay BEV",
    type: "electric",
    purchasePrice: 315000,
    annualMileage: 100000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 7800,
    insuranceCostAnnual: 9800,
    expectedLifespanYears: 15,
    fuelEfficiency: 139,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 27000,
      zugGesamtgewicht: 44000,
      achskonfiguration: "6x2",
      nutzlast: 21500,
      leistungKW: 480,
      leistungPS: 653,
      drehmoment: 2200,
      batterieKapazitaet: 738,
      reichweite: 530,
      ladeLeistungAC: 22,
      ladeLeistungDC: 350,
      fahrerhaus: "Fernverkehr",
      laenge: 6400,
      hoehe: 3950,
    },
  },
  "byd-eth8": {
    name: "BYD ETH8",
    type: "electric",
    purchasePrice: 240000,
    annualMileage: 60000,
    fuelCostPerUnit: 0.35,
    maintenanceCostAnnual: 6500,
    insuranceCostAnnual: 8500,
    expectedLifespanYears: 15,
    fuelEfficiency: 127,
    technicalSpecs: {
      zulaessigesGesamtgewicht: 19000,
      zugGesamtgewicht: 40000,
      achskonfiguration: "4x2",
      nutzlast: 12000,
      leistungKW: 300,
      leistungPS: 408,
      drehmoment: 1500,
      batterieKapazitaet: 255,
      reichweite: 200,
      ladeLeistungAC: 22,
      ladeLeistungDC: 150,
      fahrerhaus: "Nahverkehr",
      laenge: 5800,
      hoehe: 3700,
    },
  },
};

export const scenarios = pgTable("scenarios", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  dieselTruck: jsonb("diesel_truck").notNull().$type<TruckParameters>(),
  electricTruck1: jsonb("electric_truck_1").notNull().$type<TruckParameters>(),
  electricTruck2: jsonb("electric_truck_2").notNull().$type<TruckParameters>(),
  timeframeYears: integer("timeframe_years").notNull(),
  taxIncentiveRegion: text("tax_incentive_region").notNull().$type<TaxIncentiveRegion>(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertScenarioSchema = createInsertSchema(scenarios, {
  dieselTruck: truckParametersSchema,
  electricTruck1: truckParametersSchema,
  electricTruck2: truckParametersSchema,
  taxIncentiveRegion: z.enum(taxIncentiveRegions),
  timeframeYears: z.number().min(1).max(30),
}).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export type InsertScenario = z.infer<typeof insertScenarioSchema>;
export type Scenario = typeof scenarios.$inferSelect;
